version: '2'
services:
  django:
    build:
      context: ./docker
      dockerfile: Dockerfile-django
    links:
      - db
    ports:
      - 80:8000
    volumes:
      - ./:/mnt
    working_dir: /mnt
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env

  db:
    build:
      context: ./docker
      dockerfile: Dockerfile-db
    expose:
      - "5432"
    env_file: .env
